application: iron-stack-575
version: 4
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /fonts
  static_dir: fonts

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "latest"
- name: webapp2
  version: "latest"
- name: MySQLdb
  version: "latest"
  